stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.5-openjdk-22
  script:
    - mvn clean install

test:
  stage: test
  image: maven:3.8.5-openjdk-22
  script:
    - mvn test
    - mvn allure:serve
