name: Запуск тестов MTS-Reqres

on:
 push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование основного репозитория
        uses: actions/checkout@v3

      - name: Настройка JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Запуск тестов
        continue-on-error: true
        run: mvn clean test

      - name: Создание директории для Allure history
        run: mkdir -p target/allure-history

      - name: Проверка наличия результатов Allure
        run: |
          if [ ! -d "target/allure-results" ] || [ -z "$(ls -A target/allure-results)" ]; then
            echo "Allure results not found!";
            exit 1;
          fi

      - name: Генерация отчета Allure
        uses: simple-elf/allure-report-action@v1
        id: allure-report
        with:
          allure_results: target/allure-results
          allure_history: target/allure-history
          allure_report: target/allure-report

      - name: Развертывание отчета на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/allure-report
